# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-17 09:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SAuthUserDb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Пользователь <=> БД',
                'verbose_name_plural': 'Пользователи <=> БД',
                'db_table': 's_auth_user_db',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SAuthUserService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Пользователь <=> Сервис',
                'verbose_name_plural': 'Пользователи <=> Сервисы',
                'db_table': 's_auth_user_service',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SDb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True, unique=True, verbose_name='Название')),
                ('p_host', models.CharField(max_length=255, null=True, verbose_name='Сервер')),
                ('p_name', models.CharField(max_length=255, null=True, verbose_name='БД')),
                ('p_username', models.CharField(max_length=100, null=True, verbose_name='Пользователь')),
                ('p_password', models.CharField(max_length=100, null=True, verbose_name='Пароль')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Коментарий')),
                ('checked', models.BooleanField(verbose_name='Вкл.')),
            ],
            options={
                'verbose_name': 'БД',
                'verbose_name_plural': 'БД',
                'db_table': 's_db',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info', models.TextField(null=True, verbose_name='Информация')),
                ('dt', models.DateTimeField(null=True, verbose_name='Дата и время')),
            ],
            options={
                'verbose_name': 'Лог',
                'verbose_name_plural': 'Лог',
                'db_table': 's_log',
                'ordering': ['-dt'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SQuery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True, unique=True, verbose_name='Название')),
                ('script', models.TextField(null=True, verbose_name='SQL')),
                ('priority', models.IntegerField(null=True, verbose_name='Приоритет')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
                ('result', models.CharField(blank=True, max_length=255, null=True, verbose_name='Значение ответа')),
            ],
            options={
                'verbose_name': 'Запрос',
                'verbose_name_plural': 'Запросы',
                'db_table': 's_query',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True, unique=True, verbose_name='Название')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
                ('checked', models.BooleanField(verbose_name='Вкл.')),
            ],
            options={
                'verbose_name': 'Сервис',
                'verbose_name_plural': 'Сервисы',
                'db_table': 's_service',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True, unique=True, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Тип обработки запросов',
                'verbose_name_plural': 'Типы обработки запросов',
                'db_table': 's_type',
                'managed': False,
            },
        ),
    ]
